export const tapes = [
  {
    id: 1,
    title: '411VM - Issue #1',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-1-65124.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-1:7',
    soundtrack: {
      'Intro': ['Sol - The Boxcar'],
      'Jeremy Wray Profiles': ['Gibb Droll - Melting Pot'],
      'Aaron Bleasdale Wheels Of Fortune': ['Gas Huffer - George Washington'],
      'Paul Shapiro Wheels Of Fortune': ['Crash Course - Prince Of The City'],
      'Mike Hayes Wheels Of Fortune': ['Uncle! - Piano Movers'],
      'Jesse Paez Wheels Of Fortune': ['Supreme Love Gods - Nothing'],
      'Rob Carlyon Wheels Of Fortune': ['Hemi - Dog Tied Again'],
      'Sierra Tahoe Contests': ['Shovelhead - Tired And Afraid'],
      'London Metrospective': ['Odd Numbers - So Many Girls'],
      'Chaffey, Carlsbad, Pioneer, Huntington, Lockwood Schoolyards': ['Hemi - Freeloader'],
      'Playground Skatepark Street And Vert Contests': ['Funky Beatniks - Morning Void'],
      'Chaos': ['3% Fat - Causin Chaos', 'Supreme Love Gods - Fire'],
      'Grapevine': ['Gibb Droll - Unfaithful Woman'],
    },
  },
  {
    id: 2,
    title: '411VM - Issue #2',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-2-34713.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-2:0',
    soundtrack: {
      'Jason Rothmeyer Profiles': ['Bad Religion - Yesterday', 'Bad Religion - Bad Religion'],
      'Darryl Vaughn Wheels Of Fortune': ['Ringworm - Nunb'],
      'Tom Penny Wheels Of Fortune': ['Cornershop - Trip Easy'],
      'Richard Angelides Wheels Of Fortune': ['Bad Religion - Anesthesia'],
      'Tas Pappas Wheels Of Fortune': ['Daw Hammer - Vigil Smile'],
      'Moses Itkonen Wheels Of Fortune': ['Confront - Payday'],
      'Munster Vert And Street Contests': ['Rich Kids On Lsd - Insane'],
      'Belgium Street Contests': ['NOFX - The Bag'],
      'Rad Lands / Northhampton Skatepark Contests': ['Sol - Hace Calor'],
      'Back To The City 5 Contests': ["Souls of Mischief - '93 Til Infinity"],
      'Visalia Skate Camp': ['Pennywise - Time To Burn'],
      'Woodward Skate Camp': ['Gibb Droll - Plastic Shuffle'],
      'Australia, Japan, Holland, Italy, New Zealand, England World Report': [
        'Bad Religion - Automatic Man',
        'Bad Religion - I Want To Conquer The World',
        'Bad Religion - Sanity',
      ],
      'Transitions Transitions': ['The Offspring - Take It Like A Man'],
      'Rad Lands/Northhampton Skatepark Contests': ["Jacob's Mouse - Solo"],
    },
  },
  {
    id: 3,
    title: '411VM - Issue #3',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-4-4070.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-3:1',
    soundtrack: {
      'Intro': ['Sol - The Box Car'],
      'Profiles: Scott Johnston': ['Raised by Seuss - Face the Music'],
      'Wheels of Fortune: Mike Judd': [],
      'Wheels of Fortune: Javier Nunez': [],
      'Wheels of Fortune: Matt Pailes': [],
      'Wheels of Fortune: Tony Briseno': [],
      'Wheels of Fortune: Joey Bast': [],
      '60/40 Ad': ['Eazy-E - Gimmie That Nutt'],
      'Etnies Ad': [],
      'Mad Circle Ad': ['Bing Crosby - White Christmas'],
      'Birdhouse Ad': ['Kris Kross - Jump'],
      'Keep Out': ['Corduroy - High Havoc'],
      'Metrospective: Philadelphia': ['The Whooliganz - Put Your Handz Up'],
      'Contest: Houston Texas': [],
      'Fine Tuning: Greg Hunt & Mike Carroll': [],
      'Fine Tuning: Felix Arguelles': [],
      'Fine Tuning: Jan Waage': [],
      'Fine Tuning: Ron Knigge': [],
      'Fine Tuning: Simon Woodstock': [],
      'The Industry: SMA': ['NOFX - Together On The Sand', 'NOFX - Brain Constipation'],
      'Halloween': ['Mother Earth - Roadster'],
      'Plan B Ad': ['The Monkees - I\'m a Believer'],
      'Element Ad': [],
      'Contest: Thrash-A-Thon Pro Mini Ramp & Street Contest': ['Corduroy - The Corduroy Orgasm Club'],
      'World Report: Germany, Great Britain, Belgium': ['Raised by Seuss - Part of the Skeme'],
      'World Report: Sweden, Holland': ['Teddybears - Powertrip'],
      'World Report: Denmark': [],
      'Wheels of Fortune: Jeron WIlson': ['Raised by Seuss - Fly Away'],
      'Wheels of Fortune: Craig Steele': ['Raised by Seuss - Fly Away'],
      'Wheels of Fortune: Sage Humphries': [],
      'Wheels of Fortune: Klaus Dieter Span': [],
      'Transitions': ['Mother Earth - Knowledge'],
      'Switchstance': ['Mother Earth - Knowledge'],
      'Chaos': ['Mother Earth - Knowledge'],
      'Planet Earth Griptape Ad': [],
      'Skully Bros Ad': ['Jacob\'s Mouse - Dusty'],
      'Anthony Carney MSG Ad': [],
      'The National Deal League Ad': ['Corduroy - Very Yeah'],
      'Profiles: Eric Koston': [],
      'Grapevine': [],
      'NSA Pro Finals Preview': [],
      'Credits': ['Raised by Seuss - Another Graduate'],
      'Music Credits': ['Raised by Seuss - Another Graduate'],
    },
  },
  {
    id: 4,
    title: '411VM - Issue #4',
    imageUrl: 'https://static.wixstatic.com/media/6a7e42_438c6963806449738a8538bee4f54986~mv2_d_1500_1500_s_2.png/v1/fill/w_560,h_560,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/6a7e42_438c6963806449738a8538bee4f54986~mv2_d_1500_1500_s_2.png',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-4:b',
    soundtrack: {
      'Chaos Chaos': ['Jawbox - Savory'],
      'Ronnie Creager Profiles': ['Mother Earth - Almost Grown'],
      'Weston Correa Wheels Of Fortune': ['Buffalo Tom - Treehouse'],
      'Justin Ortiz Wheels Of Fortune': ['Buffalo Tom - Almost Grown'],
      'James Reed 411VM Skateboarding Issue 4': ['Buffalo Tom - Almost Grown'],
      'Jan Waage 411VM Skateboarding Issue 4': ['Buffalo Tom - Almost Grown'],
      'Richard Mulder Wheels Of Fortune': ['Das Efx - Check It Out'],
      'Nsa Pro Vert, Vintage Vert And Street Contests': ['Das Efx - Krazy Wit Da Books'],
      'Casl Finals Contests': ['Seaweed - Go Your Own Way'],
      'Honolulu Metrospective': ['Buffalo Tom - Suppose'],
      'Brewster Park Spot Check': ['Mother Earth - Time Of The Future'],
      'Australia Tour Road Trip': ['Down By Law - Air Conditioner'],
      'United Kingdom, Germany, Italy, New Zealand, France World Report': ['London Posse - How\'s Life In London'],
      'Switchstance Switchstance': ['Coolio - County Line'],
      'Transitions Transitions': ['Down By Law - At Home In The Wasteland'],
    },
  },
  {
    id: 5,
    title: '411VM - Issue #5',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-50-62803.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-5:8',
    soundtrack: {
      'Switchstance Switchstance': ['Extra Prolific - Brown Sugar'],
      'Chaos Chaos': ['Gang Starr - Code Of The Streets'],
      'Planet Earth Industry': ['De La Soul - Ego Trippin (instrumental)'],
      'San Jose Metrospective': ['Raised By Seuss - One More Week Until Supper'],
      'Kwala Australia Road Trip': ['The Specials - Gangsters'],
      'Nhs Cannery Private Property': ['Pantera - Throes Of Rejection'],
      'Climax Distribution Private Property': ['Pegboy - Witnessed'],
      'credits': ['The Stranglers - Get A Grip On Yourself'],
    },
  },
  {
    id: 6,
    title: '411VM - Issue #6',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-6-29224.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-6:4',
    soundtrack: {
      'Chaos Chaos': ['Blondie - The Tide Is High'],
      'Eric Ricks Profiles': ['Gang Starr - 2 Deep'],
      'Slam City Jam Street And Vert Contests': ['Guru - No Time To Play'],
      'Newburgh Skatepark Contests': ['Blur - For Tomorrow'],
      'Love Park Contests': ['Gang Starr - B.y.s.'],
      'Jeff Taylor Rookies': ['Solsonics - Ascension'],
      'Switchstance Switchstance': ['Gang Starr - B.y.s.'],
      'Shin Okada In Japan, United Kingdom World Report': ['The Beat - Tears Of A Clown'],
      'Transitions Transitions': ['Down By Law - 500 Miles'],
      'credits': ['Rust - Some Days Never Come'],
    },
    skaters: [
      'Eric Ricks',
      'Jeff Taylor',
      'Shin Okada',
      'Nanda Zipp',
      'Genaro Vergoglini',
      'Jason Phillips',
      'Gino Perez',
      'Bill Pepper',
      'Ben Pappas',
      'Frankie Mata',
      'Ben Liversedge',
      'Rune Glifberg',
    ],
  },
  {
    id: 7,
    title: '411VM - Issue #7',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-7-20039.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-7:8',
    soundtrack: {
      'Jamie Thomas Profiles': ['Blondie - Call Me'],
      'Bam Margera Wheels Of Fortune': ['R.p.m. - Food Of My De-rhythm'],
      'Chad Fernandez, George Nagai Wheels Of Fortune': ['DJ Takemura - Harmonium'],
      'Woodward Skate Camp': ['Stiff Little Fingers - Roots, Radicals, Rockers, Reggae'],
      'Lance Dawes In Depth': ['Time And Space - Time And Space Theme'],
      'Santa Rosa Skatepark Spot Check': ['Kurios - Spell It With J'],
      'Sweden, South Africa, Australia, UK World Report': ['Coolio - Sticky Fingers'],
      'Switchstance Switchstance': ['Moist - Push'],
      'Screaming Squeegees Private Property': ['Wizards Of Ooze - The Bone'],
      'GP Skatepark Spot Check': ['Galliano - Better All The Time'],
      'Transitions Transitions': ['Sinister Dane - Ugly Thing'],
      'credits': ['House Of Pain - Where I\'m From'],
    },
  },
  {
    id: 8,
    title: '411VM - Issue #8',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-8-8733.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-8:0',
    soundtrack: {
      'Chaos Chaos': ['Justice System - Soulstyle'],
      'Rich Colwell, Mike Maldonado Wheels Of Fortune': ['Justice System - Santana'],
      'James Riff, Matt Milligan Wheels Of Fortune': ['Federation - Life So Free'],
      'Element Industry': ['Digable Planets - 9th Wonder'],
      'Madison Wisconsin Metrospective': ['Souls of Mischief - Never No More'],
      'Pat Channita, Reese Forbes Fine Tuning': ['The Selecter - The Selecter'],
      'Visalia Skate Camp': ['Galliano - Long Time Gone'],
      'Element / New Deal / Mad Circle Road Trip': ['Justice System - Summer In The City (sunshine Blend)'],
      'SMA Road Trip': ['Fretblanket - 1941'],
      'Venice Street Grind Contests': ['Digable Planets - Graffiti'],
      'Munster Street Contests': ['Fretblanket - Junkfuelled'],
    },
  },
  {
    id: 9,
    title: '411VM - Issue #9',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-9-46857.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-9:a',
    soundtrack: {
      'Transitions Transitions': ['Fretblanket - Song In B'],
      'Andy Stone Profiles': ['Extra Prolific - Never Changing'],
      'Drake Jones Wheels Of Fortune': ['Sick Of It All - Cease Fire'],
      'Stevie Williams Wheels Of Fortune': ['Lords Of The Underground - Tic Toc'],
      'Josh Kalis Wheels Of Fortune': ['Extra Prolific - Cash Money'],
      'Chany Jeanguenin Wheels Of Fortune': ['R.p.m. - Sorti Des Ombres'],
      'Anthony Correa Wheels Of Fortune': ['R.p.m. - Sorti Des Ombres'],
      'Sonic Industry': ['Pat Benatar - Hit Me With Your Best Shot', 'Blondie - Hanging On The Telephone'],
      'New York City Metrospective': ['Lords Of The Underground - What I\'m After'],
      'Fred Gall / Simon Woodstock Fine Tuning': ['DJ Krush - Slow Chase'],
      'Jamie Thomas / Kris Markovich Fine Tuning': ['DJ Krush - Influx'],
      'Monstermash Vert And High Air Contests': ['Palmskin Productions - In A Silent Way'],
      'Newburgh Pro And Am Contests': ['Lords Of The Underground - Keepers Of The Funk'],
      'Love Park Pro And Am Contests': ['Sick Of It All - No Cure'],
      'Huntington Beach Skatepark Spot Check': ['Federation - Rusty James'],
      'Chaos Chaos': ['Extra Prolific - Is It Right?'],
      'Switchstance Switchstance': ['Guru - Take A Look'],
      'credits': ['Guru - Trust Me'],
    },
  },
  {
    id: 10,
    title: '411VM - Issue #10',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-10-34402.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-10:a',
    soundtrack: {
      'And Another Track': ['And Another Artist - And Another Song'],
    },
  },
  {
    id: 11,
    title: '411vm issue 11',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-10-34402.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-10:a?r=6CdULwobgTDPf6FTjLK9oWLTPPBmW3kj',
    soundtrack: {
      'A New Track': ['A New Artist - A New Song'],
    },
  },
  {
    id: 12,
    title: '411vm - 911',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-911-29525.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-10:a?r=6CdULwobgTDPf6FTjLK9oWLTPPBmW3kj',
    soundtrack: {
      'Track 911': ['Artist 911 - Song 911'],
    },
  },
  {
    id: 13,
    title: '411vm issue 43',
    imageUrl: 'https://abd-archive.org/wp-content/uploads/2020/09/411vm-issue-43-vhs-cover.png',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-43:3?r=6CdULwobgTDPf6FTjLK9oWLTPPBmW3kj',
    soundtrack: {
      'Track 43': ['Artist 43 - Song 43'],
    },
  },
  {
    id: 14,
    title: '411vm issue 14',
    imageUrl: 'https://assets.skatevideo.site/covers/411vm-issue-14-38056.jpg',
    videoUrl: 'https://odysee.com/$/embed/@SkateOrDie:7/411VM-Issue-14:7?r=6CdULwobgTDPf6FTjLK9oWLTPPBmW3kj',
    soundtrack: {
      'Dave Duren Profiles': ['Hum - The Pod'],
      'Rodney Torres Wheels Of Fortune': ['Mobb Deep - Give Up The Goods (Just Step)'],
      'Travis Colt Wheels Of Fortune': ['88 Fingers Louie - Pent Up'],
      'Ryan Bartsma Wheels Of Fortune': ['Minor Threat - Stumped'],
      'Battle Of The Bay Contests': ['Guru - Revelation'],
      'PSL Finals Contests': ['DJ Krush - The Nightmare Of Ungah'],
      'Hard Rock Cafe Vert Contests': ['Schleprock - Sorry'],
      'Planet Earth / Rhythm Road Trip': ['Brooklyn Funk Essentials - Blow Your Brains Out'],
      'Invisible Road Trip': ['Norman Greenbaum - Spirit In The Sky'],
      'Tour': ['Kill Holiday - Cold Shoulder'],
    },
  },
];
